language: android
android:
  components:
    - tools
    - tools
    - build-tools-24.0.1
    - android-24

    # Componentes adicionales
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Emuladores para tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-17

jdk:
  - oraclejdk8 #Supports Java 8

# Para hacer correr el emulador
before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck
